const options=[
    {
        label:"Afrikaans",
        value:"af"
    },
    {label:"Arabic",
value:"ar"},
    {label:"Azerbaijani",
    value:"az"},
    {label:"Bosnian",
     value:"bs"},
    {label:"Chinese",
value:"zh-CN or zh"},
    {label:"Dutch",
     value:"nl"},
    {label:"English",
     value:"en"},
    {label:"French",
     value:"fr"},
    {label:"German",
     value:"de"},
    {label:"Greek",
     value:"el"},
    {label:"Hindi",
     value:"hi"},
    {label:"Italian",
     value:"it"},
    {label:"Japanese",
     value:"ja"},
    {label:"Kurdish",
     value:"ku"},
    {label:"Persian",
     value:"fa"},
    {label:"Romanian",
     value:"ro"},
    {label:"Russian",
     value:"ru"},
    {label:"Spanish",
     value:"es"},
    {label:"Tatar",
     value:"tt"},
    {label:"Turkmen",
     value:"tk"},
    {label:"Uyghur",
     value:"ug"},

]
export default options;